//
// Created by clemens on 05.04.25.
//

#ifndef ROBOT_EX_HPP
#define ROBOT_EX_HPP

#define LINE_MOTOR1_PWM1 LINE_UART1_RX
#define LINE_MOTOR1_PWM1_MODE PAL_MODE_ALTERNATE(1)
#define LINE_MOTOR1_PWM2 LINE_UART1_TX
#define LINE_MOTOR1_PWM2_MODE PAL_MODE_ALTERNATE(1)
#define LINE_MOTOR1_ENCODER_A LINE_GPIO16
#define LINE_MOTOR1_ENCODER_B LINE_GPIO17
#define MOTOR1_PWM PWMD1
#define MOTOR1_PWM_CHANNEL_1 1
#define MOTOR1_PWM_CHANNEL_2 2

#define LINE_MOTOR2_PWM1 LINE_UART6_RX
#define LINE_MOTOR2_PWM1_MODE PAL_MODE_ALTERNATE(2)
#define LINE_MOTOR2_PWM2 LINE_UART6_TX
#define LINE_MOTOR2_PWM2_MODE PAL_MODE_ALTERNATE(2)
#define LINE_MOTOR2_ENCODER_A LINE_GPIO18
#define LINE_MOTOR2_ENCODER_B LINE_GPIO19
#define MOTOR2_PWM PWMD3
#define MOTOR2_PWM_CHANNEL_1 0
#define MOTOR2_PWM_CHANNEL_2 1

#define LINE_AUX_POWER_1_ENABLE LINE_GPIO10
#define LINE_AUX_POWER_1_STATUS LINE_GPIO11
#define LINE_AUX_POWER_2_ENABLE LINE_GPIO12
#define LINE_AUX_POWER_2_STATUS LINE_GPIO13
#define LINE_AUX_POWER_3_ENABLE LINE_GPIO14
#define LINE_AUX_POWER_3_STATUS LINE_GPIO15
#define LINE_POWER_1_ENABLE LINE_GPIO8
#define LINE_POWER_2_ENABLE LINE_GPIO9

#define LINE_LIDAR_POWER_ENABLE LINE_GPIO21
#define LINE_LIDAR_MOTOR_ENABLE LINE_GPIO20

#define LINE_CHARGER_ENABLE LINE_GPIO6

#define NO_MOWER_SERVICE

#endif  // ROBOT_EX_HPP
