//
// Created by clemens on 05.04.25.
//

#ifndef ROBOT_EX_HPP
#define ROBOT_EX_HPP

#define LINE_EMERGENCY_1 LINE_GPIO13
#define LINE_EMERGENCY_2 LINE_GPIO12
#define LINE_EMERGENCY_3 LINE_GPIO11
#define LINE_EMERGENCY_4 LINE_GPIO10

#endif //ROBOT_EX_HPP
